language: php

php:
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer update --prefer-source --dev

script:
  - ./vendor/bin/phpunit --group=Functional
  - ./vendor/bin/phpcs --standard=PSR2 ./src/

after_script:
  - php vendor/bin/coveralls -v

notifications:
  irc: "irc.freenode.org#zftalk.modules"
  email: false
